controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
registration:
    path: /register
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\Auth\RegistrationController::index

create_user:
    path: /createUser
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\Auth\RegistrationController::create