controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
registration:
    path: /register
    controller: App\Controller\Auth\RegistrationController::index

Login_user:
    path: /login
    controller: App\Controller\Auth\LoginController::index

create_user:
    path: /createUser
    controller: App\Controller\Auth\RegistrationController::create
